"""ai_office_shared.shared — общая библиотека для всех ботов офиса."""
# ollama fallback — imported by bots as needed
# impact_client доступен через: from ai_office_shared.shared.impact_client import ...
